%{?!ros_distro:%global ros_distro lyrical}
%global pkg_name rosapi
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

Name:           ros-lyrical-rosapi
Version:        4.1.0
Release:        3%{?dist}
Summary:        ROS %{pkg_name} package

License:        BSD
URL:            http://ros.org/wiki/rosapi
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  bloom-rpm-macros
BuildRequires:  cmake

%{?bloom_package}

%description
Provides services for getting various ROS meta-information, including ROS topic,
services, interfaces or action servers and managing ROS parameters.


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Provides:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-runtime%{?_isa} = %{version}-%{release}

%description devel
Provides services for getting various ROS meta-information, including ROS topic,
services, interfaces or action servers and managing ROS parameters.


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
Provides services for getting various ROS meta-information, including ROS topic,
services, interfaces or action servers and managing ROS parameters.


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires


%build
%cmake \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="%{bloom_prefix}" \
    -DAMENT_PREFIX_PATH="%{bloom_prefix}" \
    -DCMAKE_PREFIX_PATH="%{bloom_prefix}" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif

%cmake3_build


%install
%cmake_install


%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C %{__cmake_builddir} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
CTEST_OUTPUT_ON_FAILURE=1 \
    %cmake_build $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%{bloom_prefix}


%changelog
* Wed Apr 29 2026 Błażej Sowa <blazej@fictionlab.pl> - 4.1.0-3
- Autogenerated by Bloom

* Tue Apr 28 2026 Błażej Sowa <blazej@fictionlab.pl> - 4.1.0-2
- Autogenerated by Bloom

* Tue Apr 21 2026 Błażej Sowa <blazej@fictionlab.pl> - 4.1.0-1
- Autogenerated by Bloom
