%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/galactic/.*$
%global __requires_exclude_from ^/opt/ros/galactic/.*$

Name:           ros-galactic-rosbridge-server
Version:        1.3.1
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS rosbridge_server package

License:        BSD
URL:            http://ros.org/wiki/rosbridge_server
Source0:        %{name}-%{version}.tar.gz

Requires:       python%{python3_pkgversion}-tornado
Requires:       python%{python3_pkgversion}-twisted
Requires:       ros-galactic-rclpy
Requires:       ros-galactic-rosapi
Requires:       ros-galactic-rosbridge-library
Requires:       ros-galactic-rosbridge-msgs
Requires:       ros-galactic-ros-workspace
BuildRequires:  python%{python3_pkgversion}-autobahn
BuildRequires:  ros-galactic-ament-cmake
BuildRequires:  ros-galactic-ament-cmake-ros
BuildRequires:  ros-galactic-launch
BuildRequires:  ros-galactic-launch-ros
BuildRequires:  ros-galactic-launch-testing
BuildRequires:  ros-galactic-launch-testing-ament-cmake
BuildRequires:  ros-galactic-launch-testing-ros
BuildRequires:  ros-galactic-std-srvs
BuildRequires:  ros-galactic-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
A WebSocket interface to rosbridge.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/galactic/setup.sh" ]; then . "/opt/ros/galactic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/galactic" \
    -DAMENT_PREFIX_PATH="/opt/ros/galactic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/galactic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/galactic/setup.sh" ]; then . "/opt/ros/galactic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/galactic/setup.sh" ]; then . "/opt/ros/galactic/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/galactic

%changelog
* Fri Oct 21 2022 Jihoon Lee <jihoonlee.in@gmail.com> - 1.3.1-1
- Autogenerated by Bloom

* Tue Aug 16 2022 Jihoon Lee <jihoonlee.in@gmail.com> - 1.3.0-1
- Autogenerated by Bloom

* Fri May 20 2022 Jihoon Lee <jihoonlee.in@gmail.com> - 1.2.0-1
- Autogenerated by Bloom

* Mon Jan 03 2022 Jihoon Lee <jihoonlee.in@gmail.com> - 1.1.2-1
- Autogenerated by Bloom

* Thu Dec 09 2021 Jihoon Lee <jihoonlee.in@gmail.com> - 1.1.1-1
- Autogenerated by Bloom

* Fri Oct 22 2021 Jihoon Lee <jihoonlee.in@gmail.com> - 1.1.0-1
- Autogenerated by Bloom

* Thu Aug 26 2021 Jihoon Lee <jihoonlee.in@gmail.com> - 1.0.8-1
- Autogenerated by Bloom

* Wed Aug 18 2021 Russell Toris <rctoris@wpi.edu> - 1.0.7-1
- Autogenerated by Bloom

* Tue Aug 17 2021 Russell Toris <rctoris@wpi.edu> - 1.0.6-1
- Autogenerated by Bloom

* Thu Aug 12 2021 Russell Toris <rctoris@wpi.edu> - 1.0.5-1
- Autogenerated by Bloom

